CREATE MEMORY TABLE "PUBLIC"."MY_APPOINTMENT"(
    "SERVICE_PROVIDER_ID" INTEGER NOT NULL,
    "CLIENT_ID" INTEGER NOT NULL
);

ALTER TABLE "PUBLIC"."MY_APPOINTMENT" ADD CONSTRAINT "PUBLIC"."FKH86MO9YTCMT8DOBB615OTQ2HN" FOREIGN KEY("SERVICE_PROVIDER_ID") REFERENCES "PUBLIC"."MY_SERVICE_PROVIDER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."MY_APPOINTMENT" ADD CONSTRAINT "PUBLIC"."FKB7S45QYEPIHEFC7CTHS3QF59B" FOREIGN KEY("CLIENT_ID") REFERENCES "PUBLIC"."MY_CLIENT"("ID") NOCHECK;