CREATE TABLE My_Client_Profile (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  client_id BIGINT NOT NULL
);

ALTER TABLE My_Client_Profile ADD CONSTRAINT FK_PROFILE_CLIENT_ID FOREIGN KEY (client_id) REFERENCES My_CLIENT(id);

