CREATE TABLE My_Appointment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  client_id BIGINT NOT NULL
);

ALTER TABLE My_Appointment ADD CONSTRAINT FK_APPOINTMNET_CLIENT_ID FOREIGN KEY (client_id) REFERENCES My_CLIENT(id);

